// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.BankView = (function(superClass) {
    extend(BankView, superClass);

    function BankView() {
      return BankView.__super__.constructor.apply(this, arguments);
    }

    BankView.prototype.className = 'bank';

    BankView.prototype.initialize = function() {
      return this.model.on("change", this.render, this);
    };

    BankView.prototype.template = _.template("Bankroll: $<%- playerWallet %>");

    BankView.prototype.betTemplate = _.template('<button class="bet-button">Bet $5</button> <button class="bet-close-button">Play</button>');

    BankView.prototype.potTemplate = _.template('Pot: <div id="pot-amount"><%- currentBet %></div>');

    BankView.prototype.events = {
      'click .bet-button': _.debounce((function() {
        return this.model.addBet(5);
      }), 60, true),
      'click .bet-close-button': _.debounce((function() {
        return this.model.closeBets();
      }), 100, true)
    };

    BankView.prototype.render = function() {
      this.$el.find('#pot').html(this.potTemplate(this.model.attributes));
      if (!window.hasInterval) {
        window.hasInterval = true;
        setInterval(function() {
          return $('#pot-amount').css('color', 'hsl(' + Math.floor(Math.random() * 360) + ', 100%, 70%)');
        }, 250);
      }
      this.$el.find('#bank-controls').html(this.template(this.model.attributes));
      if (this.model.get("app").get("state") === "takeBets") {
        return this.$el.find('#bank-controls').append(this.betTemplate());
      }
    };

    return BankView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=BankView.js.map
