// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.CardView = (function(superClass) {
    extend(CardView, superClass);

    function CardView() {
      return CardView.__super__.constructor.apply(this, arguments);
    }

    CardView.prototype.className = 'card';

    CardView.prototype.template = _.template('<div></div>');

    CardView.prototype.initialize = function() {
      return this.render();
    };

    CardView.prototype.render = function() {
      var imgURL;
      this.$el.children().detach();
      imgURL = this.model.get('rankName') + '-' + this.model.get('suitName') + '.png';
      this.$el.html(this.template(this.model.attributes));
      this.$el.css('background-image', 'url("img/cards/' + imgURL + '")');
      if (!this.model.get('revealed')) {
        return this.$el.css('background-image', 'url("img/card-back.png")');
      }
    };

    return CardView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=CardView.js.map
