items = [
{"de": "ausweisen", "satz": "Am Eingang dieser Behörde muss man sich ausweisen.", "en": "identify, expel"},
{"de": "arbeitslos", "satz": "Er ist seit fünf Monaten arbeitslos.", "en": "unemployed"},
{"de": "die Haltung", "satz": "Die Regierung hat zu dieser Frage eine ablehnende Haltung.", "en": "attitude, posture"},
{"de": "erzählen", "satz": "Als ich klein war, erzählte mir meine Mutter immer Märchen.", "en": "tell"},
{"de": "spätestens", "satz": "Spätestens am vierten April müssen alle Unterlagen vorliegen.", "en": "at the latest"},
{"de": "heißen", "satz": "Wie heißt du eigentlich?", "en": "be called"},
{"de": "fügen", "satz": "Letztendlich fügte sie sich den Anordnungen ihrer Eltern.", "en": "submit, add"},
{"de": "möglicherweise", "satz": "Der Brief ist möglicherweise von meinem Freund, genau weiß ich es aber nicht.", "en": "possibly"},
{"de": "örtlich", "satz": "Örtlich kann es Regen geben.", "en": "local"},
{"de": "die Therapie", "satz": "Die Therapie hat Erfolg gehabt und der Patient ist wieder gesund.", "en": "therapy"},
{"de": "aufbewahren", "satz": "In dieser Kiste bewahrt meine Großmutter ihre alten Fotos auf.", "en": "keep, store"},
{"de": "anregen", "satz": "In der letzten Sitzung regte er an, die Ausstellung gemeinsam zu besuchen.", "en": "encourage, suggest, stimulate"},
{"de": "fremd", "satz": "Ihre Art und Weise, zu sprechen und zu handeln, ist mir fremd.", "en": "strange, foreign"},
{"de": "integrieren", "satz": "Ausländische Bürger sollten besser in unsere Gesellschaft integriert werden.", "en": "integrate"},
{"de": "die Tür", "satz": "Ich habe meinen Schlüssel verloren und kann die Tür nicht mehr öffnen.", "en": "door"},
{"de": "danach", "satz": "Erst sind wir ins Kino gegangen, danach haben wir noch etwas zusammen gegessen.", "en": "after it, afterwards"},
{"de": "Schweizer", "satz": "Schweizer Uhren können sehr teuer sein.", "en": "Swiss"},
{"de": "der Schluss", "satz": "Zum Schluss der Veranstaltung wurde klassische Musik gespielt.", "en": "end, conclusion"},
{"de": "darstellen", "satz": "Die Schauspieler stellen eine Szene aus einem Werk von Goethe dar.", "en": "depict, portray"},
{"de": "um", "satz": "Wir gingen um das Haus.", "en": "around"},
{"de": "etwa", "satz": "Geht es bei dem Gespräch etwa um deine neue Aufgabe im Betrieb?", "en": "about, approximately"},
{"de": "die Erfüllung", "satz": "In dieser Arbeit habe ich meine Erfüllung gefunden.", "en": "fulfillment"},
{"de": "potenziell", "satz": "Ich habe fünf potenzielle Käufer für das Haus gefunden.", "en": "potential"},
{"de": "der Sohn", "satz": "Sie hat einen Sohn, der fünf Jahre als ist.", "en": "son"},
{"de": "blöd", "satz": "Sei doch nicht blöd.", "en": "stupid, dumb"},
{"de": "die Philosophie", "satz": "Ich möchte später Philosophie studieren.", "en": "philosophy"},
{"de": "der Anwalt", "satz": "Der Anwalt vertritt das Opfer vor Gericht.", "en": "attorney"},
{"de": "neugierig", "satz": "Neugierigen Fragen gehe ich meistens aus dem Weg.", "en": "curious"},
{"de": "der Gast", "satz": "Heute Abend erwarten wir Gäste zum Essen.", "en": "guest"},
{"de": "früher", "satz": "Früher, als ich noch zur Schule ging, war alles anders.", "en": "in former times"},
{"de": "unglaublich", "satz": "Es ist unglaublich, was du sagst.", "en": "incredible"},
{"de": "unterliegen", "satz": "Die Mannschaft unterlag dem Gegner nur knapp.", "en": "be defeated, be subject"},
{"de": "der Verein", "satz": "Er spielt Tennis in einem Verein.", "en": "association, club"},
{"de": "unser", "satz": "Dieser junge Mann ist unser Sohn.", "en": "our"},
{"de": "das Fleisch", "satz": "Nicht alle Menschen essen gerne Fleisch.", "en": "meat, flesh"},
{"de": "der Maßstab", "satz": "Ich habe ein Modell des Autos im Maßstab 1:12 gebaut.", "en": "scale, yardstick, standard"},
{"de": "die Bemerkung", "satz": "Darf ich dazu eine Bemerkung machen?", "en": "remark, comment"},
{"de": "an", "satz": "Der Tisch steht an der Wand.", "en": "at, on"},
{"de": "dreimal", "satz": "Ich habe das Spiel dreimal gewonnen.", "en": "three times"},
{"de": "vertreiben", "satz": "Die Firma vertreibt ihre Produkte über das Internet.", "en": "sell, distribute"},
{"de": "normalerweise", "satz": "Normalerweise stehe ich früh auf, aber heute habe ich lange geschlafen.", "en": "normally"},
{"de": "die Berechnung", "satz": "Nach meiner Berechnung müssten wir 150 Euro sparen.", "en": "calculation"},
{"de": "verlangen", "satz": "Er verlangt von mir eine rasche Antwort.", "en": "request, demand"},
{"de": "moralisch", "satz": "Diese Entscheidung ist moralisch nicht zu vertreten.", "en": "moral"},
{"de": "die Tonne", "satz": "Der LKW wiegt fünf Tonnen.", "en": "ton, barrel"},
{"de": "dahin", "satz": "Ich habe schon so viel über Paris gelesen, nächste Woche reise ich dahin.", "en": "there"},
{"de": "der Boden", "satz": "Vorsicht, der Boden ist sehr glatt.", "en": "ground, floor, bottom"},
{"de": "erfolgen", "satz": "Leider erfolgte auf die Forderungen der Bürger bisher keine Reaktion.", "en": "take place, occur"},
{"de": "die Klasse", "satz": "Die Klasse macht einen Ausflug mit ihrem Lehrer.", "en": "class"},
{"de": "umstellen", "satz": "Wir müssen die Möbel umstellen, sonst ist es zu eng im Wohnzimmer.", "en": "rearrange, adjust, switch"},
{"de": "die Summe", "satz": "Die Schüler erhalten Aufgaben, in denen sie die Summe verschiedener Zahlen berechnen müssen.", "en": "sum"},
{"de": "zusammenfassen", "satz": "Sie fasst den Inhalt des Romans in einem kurzen Text zusammen.", "en": "summarize"},
{"de": "agieren", "satz": "Er agiert als Vorsitzender seiner Partei.", "en": "act"},
{"de": "strategisch", "satz": "Ein strategisches Vorgehen ist sehr wichtig.", "en": "strategic"},
{"de": "das Unrecht", "satz": "Dass es viele arme Menschen gibt, aber nur sehr wenige reiche, ist ein großes Unrecht.", "en": "injustice, wrong"},
{"de": "teuer", "satz": "Ein Haus bauen ist sehr teuer.", "en": "expensive"},
{"de": "schlagen", "satz": "Beim Tennis schlage ich mit viel Kraft gegen den Ball.", "en": "hit, beat"},
{"de": "der Apfel", "satz": "Ich esse jeden Tag einen Apfel.", "en": "apple"},
{"de": "isolieren", "satz": "Die Wände des Hauses wurden mit speziellem Material isoliert.", "en": "isolate, insulate"},
{"de": "das Märchen", "satz": "Am Abend erzählte die Großmutter den Kindern immer Märchen.", "en": "fairy tale"},
{"de": "der November", "satz": "In den Bergen ist es im November oft schon sehr kalt.", "en": "November"},
{"de": "erheben", "satz": "Auf alle Waren, die verkauft werden, wird eine Steuer erhoben.", "en": "raise"},
{"de": "speziell", "satz": "Dieses Problem ist sehr speziell.", "en": "special, specific"},
{"de": "finden", "satz": "Nach drei Stunden fand ich den Schlüssel unter meinen Büchern.", "en": "find"},
{"de": "der Abstand", "satz": "Bei schlechtem Wetter sollte man mehr Abstand zu anderen Autos halten.", "en": "distance"},
{"de": "das Ei", "satz": "Ich esse zum Frühstück gerne ein gekochtes Ei.", "en": "egg"},
{"de": "der Rat", "satz": "Mein Arzt gab mir den Rat, mit dem Rauchen aufzuhören.", "en": "advice"},
{"de": "kümmern", "satz": "Sie kümmert sich ganz allein um ihre Großmutter.", "en": "take care of, be concerned"},
{"de": "der Erreger", "satz": "Häufig sind die Erreger schwerer Krankheiten noch unbekannt.", "en": "virus, germ, agent"},
{"de": "das Leid", "satz": "Kriege bringen Armut und Leid über die Menschen.", "en": "sorrow, grief"},
{"de": "derartig", "satz": "Derartige Bilder habe ich noch nicht gesehen - sie sind schön.", "en": "such, like that"},
{"de": "der, die, das", "satz": "Im Deutschen kann man sagen: der, die oder das Joghurt.", "en": "the"},
{"de": "die Auseinandersetzung", "satz": "Zwischen beiden Parteien kam es zu einer heftigen Auseinandersetzung.", "en": "argument, quarrel"},
{"de": "die Ausstellung", "satz": "Die Ausstellung wird am Wochenende eröffnet.", "en": "exhibition"},
{"de": "der Erzähler", "satz": "Erzähler von Märchen haben oft eine tiefe und warme Stimme.", "en": "storyteller, narrator"},
{"de": "der Überblick", "satz": "Zu Beginn des Semesters wird ein Überblick gegeben.", "en": "overview, view"},
{"de": "der Bauer", "satz": "Ich kaufe einige Lebensmittel direkt beim Bauern.", "en": "farmer"},
{"de": "nachträglich", "satz": "Nachträglich hat mir mein Verhalten leidgetan.", "en": "later, belated"},
{"de": "dienen", "satz": "Er hat zehn Jahre lang als Soldat in mehreren Krisengebieten gedient.", "en": "serve"},
{"de": "das Konto", "satz": "Die Miete ist bereits seit Montag auf Ihrem Konto.", "en": "account"},
{"de": "die Wende", "satz": "1989 erfolgte eine politische Wende in Deutschland.", "en": "change (esp. the 1989-90 political change in the GDR)"},
{"de": "der Arbeitsplatz", "satz": "Ich bin froh, für die nächsten zwei Jahre einen sicheren Arbeitsplatz zu haben.", "en": "workplace, job"},
{"de": "der Anfang", "satz": "Der Film war am Anfang langweilig, dann aber sehr spannend.", "en": "beginning"},
{"de": "die Begeisterung", "satz": "Mit großer Begeisterung unterstützen sie ihre Mannschaft.", "en": "enthusiasm"},
{"de": "sollen", "satz": "Der Arzt sagt, ich soll gesünder leben.", "en": "should, ought to"},
{"de": "ablösen", "satz": "Der Beamte löst seinen Kollegen um 18 Uhr vom Dienst ab.", "en": "take off, come off, peel off"},
{"de": "erzielen", "satz": "Er hat in den Prüfungen ein gutes Ergebnis erzielt.", "en": "achieve, reach"},
{"de": "anstreben", "satz": "Natürlich strebe ich in den Prüfungen ein gutes Ergebnis an.", "en": "aim at, strive"},
{"de": "zerreißen", "satz": "Bei dem Unfall hat der Junge seine Hose zerrissen.", "en": "tear (up, pieces)"},
{"de": "lesen", "satz": "In Deutsch lesen wir zurzeit Gedichte von Goethe.", "en": "read"},
{"de": "dauerhaft", "satz": "Das Wetter soll dauerhaft schön bleiben.", "en": "lasting"},
{"de": "angenehm", "satz": "Die Musik in dieser Bar ist nicht so laut. Das ist sehr angenehm.", "en": "pleasant"},
{"de": "die Statistik", "satz": "Aktuelle Statistiken belegen, dass sich Kinder heutzutage zu wenig bewegen.", "en": "statistics"},
{"de": "die Sicherung", "satz": "Er stellte fest, dass die Störung durch eine lockere Sicherung hervorgerufen wurde.", "en": "protection, fuse"},
{"de": "die Rose", "satz": "Rosen sind Blumen, die sehr viel Pflege brauchen.", "en": "rose"},
{"de": "die Skala", "satz": "Bitte schätzen Sie ihre Leistung auf einer Skala von eins bis zehn ein.", "en": "scale, range, dial"},
{"de": "wirtschaftlich", "satz": "Das Land steckt in einer wirtschaftlichen Krise.", "en": "economic, financial"},
{"de": "abreißen", "satz": "Die alten Häuser in dieser Straße werden demnächst abgerissen.", "en": "tear (down, off), not stop"},
{"de": "weiterhin", "satz": "Das Telefonieren in Flugzeugen bleibt eventuell weiterhin verboten.", "en": "still, furthermore"},
{"de": "letzte (r, s)", "satz": "Letzten Dienstag habe ich meine Tasche im Bus liegen lassen.", "en": "last"},
{"de": "vermuten", "satz": "Die Polizei vermutet, dass die Täter durch das Fenster kamen.", "en": "assume, suspect"},
{"de": "ausdrücken", "satz": "Susan kann sich sehr gut auf Italienisch ausdrücken.", "en": "express"},
{"de": "der Kauf", "satz": "Wir hoffen, Sie waren mit dem Kauf zufrieden.", "en": "purchase"},
{"de": "relativ", "satz": "Ich kenne ihn relativ gut.", "en": "relative"},
{"de": "neigen", "satz": "Er neigte sich vor, um ihr die Hand zu geben.", "en": "bend, lean"},
{"de": "die Beratung", "satz": "Ich gehe einmal im Jahr zu einer finanziellen Beratung.", "en": "consultation, advice, discussion"},
{"de": "wütend", "satz": "Mattias war so wütend, dass er ohne ein weiteres Wort das Haus verließ.", "en": "furious"},
{"de": "der Ring", "satz": "Diesen wertvollen Ring hat mir mein Mann geschenkt.", "en": "ring"},
{"de": "vorwerfen", "satz": "Der Staatsanwalt wirft dem Täter vor, Geld gestohlen zu haben.", "en": "accuse, reproach"},
{"de": "der Text", "satz": "Beim Studium müssen viele Texte in Englisch gelesen werden.", "en": "text"},
{"de": "überstehen", "satz": "Sie hat den Verlust ihres Vaters nur schwer überstanden.", "en": "get over, survive"},
{"de": "denn", "satz": "Am Sonntag arbeite ich nicht, denn es ist mein einziger freier Tag in der Woche.", "en": "because"},
{"de": "mein", "satz": "Mein Nachbar ist sehr nett.", "en": "my, mine"},
{"de": "das Gegenteil", "satz": "Das Gegenteil von gut ist böse.", "en": "opposite"},
{"de": "der Mond", "satz": "Wenn es Nacht wird, geht der Mond auf.", "en": "moon"},
{"de": "passieren", "satz": "Bei dem Unfall ist ihr nichts passiert.", "en": "take place, happen"},
{"de": "die Kartoffel", "satz": "Die Kartoffel ist in Deutschland ein beliebtes Nahrungsmittel.", "en": "potato"},
{"de": "der Quadratmeter", "satz": "Das Grundstück hat eine Fläche von 1000 Quadratmetern.", "en": "square meter"},
{"de": "das Tuch", "satz": "Sie trägt ein grünes Tuch um den Hals.", "en": "cloth"},
{"de": "bezüglich", "satz": "Ich habe eine Frage bezüglich des Antrags.", "en": "regarding"},
{"de": "das Metall", "satz": "Er benutzt eine Maschine, mit der er dickes Metall schneiden kann.", "en": "metal"},
{"de": "der Strand", "satz": "Der schmale Strand ist an einzelnen Stellen von Wasser bedeckt.", "en": "beach"},
{"de": "die Subvention", "satz": "Viele deutsche Unternehmen erhalten staatliche Subventionen.", "en": "subsidy"},
{"de": "auf", "satz": "Im Urlaub sind wir auf einen hohen Berg gestiegen.", "en": "on, at, in"},
{"de": "elf", "satz": "", "en": "eleven"},
{"de": "aufbrechen", "satz": "Gestern Nacht wurde mein Auto aufgebrochen.", "en": "break open, take off"},
{"de": "binden", "satz": "Sie band ihrer Tochter die Haare mit einem Tuch.", "en": "tie, bind"},
{"de": "der Juni", "satz": "Im Juni haben viele meiner Freunde Geburtstag.", "en": "June"},
{"de": "die Ansicht", "satz": "Bei der Ansicht des Gebirges bekam ich große Lust zu wandern.", "en": "view"},
{"de": "der Umsatz", "satz": "Die Firma konnte ihren Umsatz in diesem Jahr auf 3 Millionen Euro steigern.", "en": "turnover, sales"},
{"de": "abbauen", "satz": "Die Unternehmer planen, weitere Arbeitsplätze im Bereich der Industrie abzubauen.", "en": "reduce, dismantle"},
{"de": "immerhin", "satz": "Immerhin konntest du zur Arbeit gehen und musstest nicht zu Hause bleiben.", "en": "after all"},
{"de": "der Kanzler", "satz": "Der Kanzler wird für vier Jahre gewählt.", "en": "chancellor"},
{"de": "stellen", "satz": "Ich stelle die Tassen in den Schrank.", "en": "put, place, set"},
{"de": "der Kontakt", "satz": "Der Kontakt zu meinen Freunden ist sehr wichtig für mich.", "en": "contact"},
{"de": "längst", "satz": "Ich hätte mich schon längst von ihm trennen sollen.", "en": "long since, a long time ago"},
{"de": "ändern", "satz": "Ich finde es nicht gut, dass er ständig seine Meinung ändert.", "en": "change"},
{"de": "hinüber", "satz": "Sie müssen hinüber auf die andere Seite gehen.", "en": "over, across"},
{"de": "das Verbrechen", "satz": "Einbruch ist ein Verbrechen.", "en": "crime"},
{"de": "die Dienstleistung", "satz": "Eine Liste unserer Dienstleistungen finden Sie im Internet.", "en": "service"},
{"de": "die Firma", "satz": "Unsere Firma hat den Auftrag bekommen.", "en": "firm, company"},
{"de": "empfangen", "satz": "Sie empfing die Gäste sehr herzlich.", "en": "receive"},
{"de": "ausnehmen", "satz": "Bevor du sie kochst, musst du die Fische noch ausnehmen.", "en": "exempt, gut"},
{"de": "abholen", "satz": "Kannst du bitte das Paket von der Post abholen?", "en": "get, fetch, pick up"},
{"de": "der Zahn", "satz": "Ich muss zum Arzt, weil mein Zahn behandelt werden muss.", "en": "tooth"},
{"de": "die Hochzeit", "satz": "Ein Jahr nach der Hochzeit haben sie sich schon wieder scheiden lassen.", "en": "wedding"},
{"de": "die Masse", "satz": "Dieses Schiff hat eine Masse von 40 Tonnen.", "en": "mass, crowd"},
{"de": "der Flughafen", "satz": "Mit dem Taxi braucht man 20 Minuten bis zum Flughafen.", "en": "airport"},
{"de": "die Verknüpfung", "satz": "Eine Verknüpfung der beiden Elemente ist sehr schwierig.", "en": "combination, link"},
{"de": "der Sender", "satz": "Sie hört am liebsten englische Sender.", "en": "broadcasting station"},
{"de": "wann", "satz": "Frag ihn bitte, wann er heute nach Hause kommt.", "en": "when"},
{"de": "palästinensisch", "satz": "In den palästinensischen Gebieten ist die politische Lage unsicher.", "en": "Palestinian"},
{"de": "die Zusammensetzung", "satz": "Die Zusammensetzung des Medikaments ist neu.", "en": "composition"},
{"de": "die Erscheinung", "satz": "In der Gesellschaft wird auf die äußere Erscheinung viel Wert gelegt.", "en": "phenomenon, appearance"},
{"de": "klären", "satz": "Sie klärten alle Fragen in einem persönlichen Gespräch.", "en": "clarify, clear up"},
{"de": "das Grundgesetz", "satz": "In Deutschland ist das Grundgesetz die rechtliche Basis für alle Menschen.", "en": "constitution, basic law"},
{"de": "der Begriff", "satz": "Ich habe die Begriffe dafür schon wieder vergessen.", "en": "term, concept, idea"},
{"de": "der Anbieter", "satz": "Dieses Restaurant arbeitet mit einem sehr zuverlässigen Anbieter für frisches Gemüse zusammen.", "en": "supplier"},
{"de": "die Nahrung", "satz": "Die Menschen in dieser Region brauchen jetzt dringend Nahrung und Medikamente.", "en": "nourishment, food"},
{"de": "der Tourist", "satz": "Alle Touristen, die nach China kommen, wollen einmal die Große Mauer sehen.", "en": "tourist"},
{"de": "der Mieter", "satz": "Die Mieter haben sich über die hohen Kosten geärgert.", "en": "tenant"},
{"de": "Fachleute", "satz": "Zur öffentlichen Diskussion wurden viele Fachleute eingeladen.", "en": "experts"},
{"de": "der Teppich", "satz": "Für den Empfang des Präsidenten wird vor dem Eingang ein roter Teppich ausgelegt.", "en": "carpet"},
{"de": "der Topf", "satz": "Die Kartoffeln kocht man am besten in einem großen Topf.", "en": "pot"},
{"de": "die Auswahl", "satz": "Wir haben mehrere Modelle zur Auswahl.", "en": "choice, selection"},
{"de": "nichts", "satz": "Kurz vor dem Auftritt will er nichts essen.", "en": "nothing"},
{"de": "die Angabe", "satz": "Hier muss man Angaben wie Name, Alter und Adresse eintragen.", "en": "information, statement"},
{"de": "ungewöhnlich", "satz": "Für eine Hochzeit ist dieses Kleid ungewöhnlich. Aber es sieht sehr gut aus.", "en": "unusual"},
{"de": "der Konsument", "satz": "Vielen Konsumenten ist es nicht egal, wie ihre Lebensmittel produziert werden.", "en": "consumer"},
{"de": "die Beobachtung", "satz": "Bei genauer Beobachtung lassen sich feine Strukturen erkennen.", "en": "observation"},
{"de": "vorläufig", "satz": "Es wurde zunächst eine vorläufige Entscheidung getroffen.", "en": "temporary"},
{"de": "durchaus", "satz": "Das ist durchaus richtig, aber ich verstehe es immer noch nicht.", "en": "absolutely"},
{"de": "damit", "satz": "Sie nahm den Brief und ging damit zur Post.", "en": "with it"},
{"de": "die Kompetenz", "satz": "Ihm fehlt die nötige Kompetenz für diese Aufgabe.", "en": "competence, authority"},
{"de": "zustande", "satz": "Der Vertrag ist nach langer Zeit zustande gekommen.", "en": "come about, in existence"},
{"de": "die Pflege", "satz": "Hier bekommt der Patient die beste Pflege.", "en": "care"},
{"de": "prüfen", "satz": "Morgen werde ich im Fach Chemie geprüft.", "en": "examine, check, test"},
{"de": "umfangreich", "satz": "Er hat sehr umfangreiche Studien zu diesem Thema gemacht.", "en": "extensive"},
{"de": "erwischen", "satz": "Die Polizei konnte die Täter gerade noch erwischen.", "en": "catch"},
{"de": "die Mama", "satz": "Mein erstes Wort war Mama.", "en": "mamma"},
{"de": "sitzen", "satz": "Die Kinder sitzen auf der Wiese im Garten.", "en": "sit"},
{"de": "trotz", "satz": "Trotz seiner Krankheit fuhr er in Urlaub.", "en": "in spite of"},
{"de": "der Anschluss", "satz": "Sie haben in Köln Anschluss an den Intercity nach Hamburg.", "en": "connection"},
{"de": "literarisch", "satz": "Mein Bruder ist literarisch sehr interessiert und möchte Schriftsteller werden.", "en": "literary"},
{"de": "der Charakter", "satz": "Meine Schwester hat einen schwierigen Charakter.", "en": "character"},
{"de": "die Übertragung", "satz": "Viele Restaurants zeigen die Übertragung des Spiels.", "en": "transmission, broadcast"},
{"de": "das Spiel", "satz": "Das Spiel endete mit einem Sieg für unsere Mannschaft.", "en": "game"},
{"de": "die Waffe", "satz": "Er hat seine Waffe auf den Boden gelegt und dann kam die Polizei.", "en": "weapon"},
{"de": "werben", "satz": "Im Fernsehen darf man nicht mehr für Zigaretten werben.", "en": "advertise"},
{"de": "treffen", "satz": "Ich treffe mich am Sonntag mit meinem Bruder zum Essen.", "en": "meet"},
{"de": "vermehrt", "satz": "Deutsche Studenten gehen vermehrt ins Ausland.", "en": "increased"},
{"de": "links", "satz": "An der Ecke musst du nach links fahren.", "en": "on the left"},
{"de": "der Weg", "satz": "Dies ist der schnellste Weg zum Bahnhof.", "en": "path, way"},
{"de": "die Anpassung", "satz": "Die Anpassung der Löhne an die höheren Preise ist notwendig.", "en": "adaptation"},
{"de": "womit", "satz": "Unser Sohn will sein Studium abbrechen, womit wir nicht einverstanden sind.", "en": "with which, with what"},
{"de": "das Rad", "satz": "An meinem Auto muss ein Rad gewechselt werden.", "en": "wheel"},
{"de": "wahnsinnig", "satz": "Er ist vor Angst fast wahnsinnig geworden.", "en": "insane"},
{"de": "fortsetzen", "satz": "Die Schüler werden morgen die Analyse des Textes fortsetzen.", "en": "continue"},
{"de": "inwieweit", "satz": "Inwieweit die Situation besser geworden ist, ist noch nicht bekannt.", "en": "what extent"},
{"de": "mehr", "satz": "Das sind zu wenig Getränke, für die Party brauchen wir noch mehr.", "en": "more"},
{"de": "das Ergebnis", "satz": "Das gute Ergebnis hat mich sehr gefreut.", "en": "result"},
{"de": "brüllen", "satz": "Der Chef brüllte so laut, dass es alle Kollegen hören konnten.", "en": "bellow, roar, shout"},
{"de": "der Vordergrund", "satz": "Im Vordergrund der Ausstellung stehen Bilder, aber auch andere Dinge kann man sehen.", "en": "foreground"},
{"de": "der Soldat", "satz": "Viele deutsche Soldaten sind im Ausland im Einsatz.", "en": "soldier"},
{"de": "die Katastrophe", "satz": "Es war eine Katastrophe, viele Menschen sind gestorben.", "en": "catastrophe"},
{"de": "erhoffen", "satz": "Er hat sich von dem gemeinsamen Urlaub viel erhofft.", "en": "expect, hope for"},
{"de": "alltäglich", "satz": "Wir haben heute nur über alltägliche Dinge gesprochen.", "en": "usual, ordinary, daily"},
{"de": "daher", "satz": "Deine Müdigkeit kommt daher, dass du so wenig schläfst.", "en": "from there, therefore"},
{"de": "die Nachricht", "satz": "Er hat mir eine Nachricht geschickt, wann wir uns treffen können.", "en": "news, message"},
{"de": "mitten", "satz": "Das Stadion liegt mitten in der Stadt.", "en": "in the middle"},
{"de": "der Gegner", "satz": "Seine Gegner waren besser, er hat verloren.", "en": "opponent, competitor, enemy"},
{"de": "behindert", "satz": "Sie hat ein behindertes Kind.", "en": "handicapped"},
{"de": "herauskommen, rauskommen", "satz": "Wann soll eigentlich die neue Lebensmittelverordnung unserer Regierung herauskommen?", "en": "come out"},
{"de": "der Schmerz", "satz": "Sie hat schon seit Tagen heftige Schmerzen in den Füßen.", "en": "pain, grief"},
{"de": "zurücktreten", "satz": "Nach heftigen Protesten aus der Bevölkerung ist die Regierung nun zurückgetreten.", "en": "step back, resign"},
{"de": "unterscheiden", "satz": "Das Amt unterscheidet verschiedene Arten von Einkommen.", "en": "distinguish"},
{"de": "national", "satz": "Die nationalen Interessen aller Länder müssen berücksichtigt werden.", "en": "national"},
{"de": "die Epoche", "satz": "In diesem Buch findet man Elemente aus verschiedenen Epochen.", "en": "epoch"},
{"de": "die Persönlichkeit", "satz": "Mit seiner schwierigen Persönlichkeit passt er nicht so gut ins Team.", "en": "personality, celebrity"},
{"de": "Unterlagen", "satz": "Die Unterlagen müssen rechtzeitig der Behörde vorliegen.", "en": "documents"},
{"de": "der Ärger", "satz": "Wenn das Auto nicht mehr funktioniert, bekomme ich viel Ärger.", "en": "trouble, annoyance"},
{"de": "der Schauspieler", "satz": "Dieser Schauspieler spielt in Filmen meist einen Helden.", "en": "actor"},
{"de": "der Sportler", "satz": "Die Sportler treffen sich einmal in der Woche zum Training.", "en": "athlete"},
{"de": "absurd", "satz": "Sein Verhalten ist absurd.", "en": "absurd"},
{"de": "die Einführung", "satz": "In der ersten Woche bekommen die Studenten eine Einführung, danach müssen sie selbstständig arbeiten.", "en": "introduction"},
{"de": "achten", "satz": "Jemanden zu achten bedeutet, ihm mit Respekt zu begegnen.", "en": "respect, pay attention"},
{"de": "die Fluggesellschaft", "satz": "Die Lufthansa ist eine bekannte deutsche Fluggesellschaft.", "en": "airline"},
{"de": "zukommen", "satz": "Im Fach Geschichte kommt der Arbeit mit historischen Texten eine besondere Bedeutung zu.", "en": "come towards, be in store"},
{"de": "der Frieden", "satz": "Seit etwa einem Jahr herrscht Frieden und es wird nicht mehr gekämpft.", "en": "peace"},
{"de": "abziehen", "satz": "Frieden wird erst herrschen, wenn alle Truppen abziehen.", "en": "take off, withdraw, subtract"},
{"de": "real", "satz": "Die Hochzeit ist fast zu schön, um real zu sein.", "en": "real"},
{"de": "überziehen", "satz": "Er hat sein Konto um tausend Euro überzogen.", "en": "overdraw, cover, put on,"},
{"de": "online", "satz": "Heutzutage kann man auch online einkaufen.", "en": "online"},
{"de": "die Zwiebel", "satz": "Wenn man eine Zwiebel schneidet, muss man weinen.", "en": "onion, bulb"},
{"de": "das Bedenken", "satz": "Ich habe in dieser Angelegenheit meine Bedenken.", "en": "concern, doubt"},
{"de": "das Thema", "satz": "Skandale sind ein beliebtes Thema in den Medien.", "en": "subject, topic, theme"},
{"de": "die Anzahl", "satz": "Die Anzahl der kranken Kinder stieg jeden Winter ein bisschen.", "en": "number"},
{"de": "passen", "satz": "Diese Hose passt mir hervorragend.", "en": "fit"},
{"de": "klar", "satz": "Bei klarer Sicht kann man das Meer sehen.", "en": "clear"},
{"de": "umfassen", "satz": "Der Roman umfasst tausend Seiten.", "en": "consist of, include"},
{"de": "finanzieren", "satz": "Wie wollt ihr eigentlich das Auto finanzieren?", "en": "finance"},
{"de": "scharf", "satz": "Tut mir leid, aber indisches Essen ist mir zu scharf.", "en": "hot"},
{"de": "verabschieden", "satz": "Als es spät wurde, verabschiedeten sich die ersten Gäste der Party.", "en": "say goodbye, pass"},
{"de": "der Kompromiss", "satz": "Trotz unterschiedlicher Meinungen haben wir einen guten Kompromiss gefunden.", "en": "compromise"},
{"de": "der Fluss", "satz": "Viele große Städte liegen an einem Fluss.", "en": "river"},
{"de": "der Vortrag", "satz": "Der Vortrag war interessant, aber ich habe nicht alles verstanden.", "en": "lecture, speech"},
{"de": "die Grenze", "satz": "An der Grenze kontrollieren Soldaten den Pass.", "en": "border, frontier"},
{"de": "das Dunkel", "satz": "Die wenigen Lampen machen das Dunkel der Nacht nicht heller.", "en": "darkness"},
{"de": "der Zeitraum", "satz": "Im Zeitraum von morgens neun Uhr bis mittags zwölf Uhr habe ich immer viel zu tun.", "en": "period of time"},
{"de": "die Kombination", "satz": "Das Studium ist eine Kombination aus Theorie und Praxis.", "en": "combination"},
{"de": "die Beteiligung", "satz": "Die hohe Beteiligung an der Wahl war nicht erwartet.", "en": "participation"},
{"de": "rechte (r, s)", "satz": "Auf der rechten Seite befindet sich das Rathaus.", "en": "right"},
{"de": "entsprechend", "satz": "Wir planen das Projekt entsprechend Ihrem Vorschlag.", "en": "in accordance, accordingly"},
{"de": "der Hintergrund", "satz": "Vor dem Hintergrund des Krieges ist ein Eingreifen anderer Staaten unbedingt notwendig.", "en": "background"},
{"de": "digital", "satz": "Digitale Kameras werden immer besser.", "en": "digital"},
{"de": "die Werkstatt", "satz": "Wenn das Auto nicht fährt, muss es zur Reparatur in die Werkstatt.", "en": "workshop, garage"},
{"de": "das Motiv", "satz": "Das Motiv der Tat ist unbekannt.", "en": "motive"},
{"de": "verbessern", "satz": "Sie konnte ihre Note in Physik durch den letzten Test verbessern.", "en": "improve, correct"},
{"de": "flüchten", "satz": "Nach dem Unfall flüchtete der Fahrer über die Grenze ins Ausland.", "en": "flee"},
{"de": "locker", "satz": "Ich bin dünner geworden, meine Hose ist ganz locker.", "en": "loose, relaxed"},
{"de": "beispielsweise", "satz": "Ich spreche viele Sprachen, beispielsweise auch Englisch.", "en": "for example"},
{"de": "zwischendurch", "satz": "Wenn ich zwischendurch Hunger bekomme, esse ich einen Apfel.", "en": "in between"},
{"de": "kennzeichnen", "satz": "Ihr Verhalten kennzeichnet sie als eine sehr zuverlässige Person.", "en": "characterize, mark"},
{"de": "ohne", "satz": "Gibt es in diesem Restaurant Essen ohne Fleisch?", "en": "without"},
{"de": "der Fleck", "satz": "Du hast da einen Fleck auf der Jacke. Die muss mal gewaschen werden.", "en": "stain"},
{"de": "beschränken", "satz": "Die Behörde beschränkt die finanzielle Förderung des Projekts auf ein Jahr.", "en": "restrict"},
{"de": "braun", "satz": "Das Kind hat große braune Augen und dunkle Locken.", "en": "brown"},
{"de": "derjenige, diejenige, dasjenige", "satz": "Diejenige Frau, die ihren Garten verkaufen möchte, kenne ich gut.", "en": "the one (who, that)"},
{"de": "interkulturell", "satz": "In diesem Sommer findet wieder ein interkulturelles Treffen von Jugendlichen statt.", "en": "intercultural"},
{"de": "die Praxis", "satz": "Die Praxis von unserem Arzt befindet sich im Haus gegenüber.", "en": "practice, doctor’s office"},
{"de": "steuern", "satz": "Es ist gar nicht so leicht, moderne Technik zu steuern.", "en": "steer, control"},
{"de": "merkwürdig", "satz": "Er verhält sich manchmal etwas merkwürdig.", "en": "strange"},
{"de": "symbolisch", "satz": "Die Farbe Rot steht symbolisch für Liebe.", "en": "symbolic"},
{"de": "der Wahlkampf", "satz": "Im Wahlkampf sind die Parteien nicht immer ehrlich mit der Bevölkerung.", "en": "election campaign"},
{"de": "der Reiz", "satz": "Das helle Licht übt einen starken Reiz auf ihre Augen aus.", "en": "stimulus, appeal"},
{"de": "der Engel", "satz": "Ich glaube, dass jeder Mensch einen Engel hat, der ihm in schwierigen Situationen hilft.", "en": "angel"},
{"de": "rücken", "satz": "Könntest du bitte deinen Stuhl etwas zur Seite rücken?", "en": "move"},
{"de": "die Spalte", "satz": "Die Tabelle hat fünf Spalten.", "en": "column, fissure, cleft"},
{"de": "der Hersteller", "satz": "Die Messe ist interessant für Hersteller und Konsumenten.", "en": "manufacturer, producer"},
{"de": "überfordern", "satz": "Diese Aufgabe hat die Schüler vollkommen überfordert.", "en": "overtax, be too much"},
{"de": "der Leser", "satz": "Für manche Leser sind die Informationen weniger wichtig als die Unterhaltung.", "en": "reader"},
{"de": "hereinkommen, reinkommen", "satz": "Als sie zur Tür hereinkam, wurde sie sofort von ihren Kindern begrüßt.", "en": "come in"},
{"de": "chinesisch", "satz": "Die chinesische Schrift ist nicht leicht.", "en": "Chinese"},
{"de": "das Wunder", "satz": "Es gibt Wunder, die man nicht erklären kann.", "en": "miracle"},
{"de": "selbstverständlich", "satz": "Es ist selbstverständlich, dass ich dir bei deinem Umzug helfe.", "en": "obvious, certainly, of course"},
{"de": "das Flugzeug", "satz": "Am schnellsten reist man mit dem Flugzeug.", "en": "airplane"},
{"de": "der Höhepunkt", "satz": "Der Auftritt von Madonna ist der Höhepunkt des Festivals in diesem Jahr.", "en": "high point, peak"},
{"de": "empirisch", "satz": "Ich habe meine Meinung mit empirischen Daten begründet.", "en": "empirical"},
{"de": "wovon", "satz": "Kannst du mir sagen, wovon du das neue Auto bezahlen willst?", "en": "from what, about what"},
{"de": "entschließen ", "satz": "Er entschloss sich, sein Studium an einer anderen Universität fortzusetzen.", "en": "decide"},
{"de": "hoffen", "satz": "Die Mutter hofft, ihren Sohn bald wiederzusehen.", "en": "hope"},
{"de": "heiraten", "satz": "Meine Schwester heiratet in einem Monat ihren langjährigen Freund.", "en": "marry"},
{"de": "das Geräusch", "satz": "Weißt du, wo das komische Geräusch herkommt?", "en": "sound, noise"},
{"de": "mehrere", "satz": "Gestern war ich mehrere Stunden in der Stadt und habe einige Freunde getroffen.", "en": "several"},
{"de": "fern", "satz": "Ich reise gerne in ferne Länder.", "en": "far, distant"},
{"de": "der Kanton", "satz": "Die Schweiz besteht aus 26 Kantonen.", "en": "canton (Switzerland), province"},
{"de": "arabisch", "satz": "Die arabische Sprache ist schwer.", "en": "Arabian, Arabic"},
{"de": "einstellen", "satz": "Unser Betrieb stellt in diesem Monat zehn neue Mitarbeiter ein.", "en": "employ, adjust, stop"},
{"de": "wunderbar", "satz": "Das Essen schmeckt ganz wunderbar! Vielen Dank fürs Kochen!", "en": "wonderful"},
{"de": "üben", "satz": "Du musst heute noch für die Schule üben.", "en": "practice"},
{"de": "beziehungsweise, bzw.", "satz": "Ich wohne ich Dresden beziehungsweise in der Nähe von Dresden.", "en": "or, respectively"},
{"de": "bedienen", "satz": "In diesem Restaurant wird man immer sehr gut bedient.", "en": "serve, operate"},
{"de": "die Operation", "satz": "Nach einer Operation muss man oft noch ein paar Tage im Krankenhaus bleiben.", "en": "operation, surgery"},
{"de": "hundert", "satz": "", "en": "hundred"},
{"de": "acht", "satz": "", "en": "eight"},
{"de": "der Ton", "satz": "Beim Singen trifft sie auch die ganz hohen Töne.", "en": "sound, tone, clay"},
{"de": "tausend", "satz": "", "en": "thousand"},
{"de": "konfrontieren", "satz": "Ständig werden die Bürger mit neuen Reformen konfrontiert.", "en": "confront"},
{"de": "das Schiff", "satz": "Die Schiffe fahren hinaus auf das Meer.", "en": "ship"},
{"de": "die Szene", "satz": "Die erste Szene des Films spielt in einem Garten.", "en": "scene"},
{"de": "leicht", "satz": "Die Tasche ist leichter, als ich dachte.", "en": "light, easy"},
{"de": "das Regal", "satz": "Wir müssen noch das Regal im Wohnzimmer anbringen.", "en": "shelf"},
{"de": "der Offizier", "satz": "Sein Großvater war im Zweiten Weltkrieg Offizier bei der französischen Armee.", "en": "officer"},
{"de": "das Bedürfnis", "satz": "Ich habe das Bedürfnis, mich zu bewegen.", "en": "need"},
{"de": "drüben", "satz": "Er steht drüben auf der anderen Seite der Straße.", "en": "over there"},
{"de": "passieren", "satz": "Seit dem Regierungswechsel ist viel in diesem Land passiert.", "en": "take place, happen"},
{"de": "jede (r, s)", "satz": "Er spielt jeden Sonntag mit Freunden Fußball.", "en": "every"},
{"de": "entgegenkommen", "satz": "Aus Richtung Markt kamen uns viele Fahrzeuge entgegen.", "en": "come towards, come to meet,"},
{"de": "der Gott", "satz": "Viele Menschen, die an Gott glauben, gehen am Sonntag in die Kirche.", "en": "god"},
{"de": "die Mauer", "satz": "Um das Haus des Präsidenten hat man eine hohe Mauer gebaut.", "en": "wall"},
{"de": "dunkel", "satz": "Es ist so dunkel, dass man die Hand vor Augen nicht mehr sieht.", "en": "dark"},
{"de": "der Nerv", "satz": "Die Nerven bilden im Körper ein ganzes System.", "en": "nerve"},
{"de": "die Ruhe", "satz": "Wenn sie von der Arbeit nach Hause kommt, hat sie nur noch das Bedürfnis nach Ruhe.", "en": "silence, peace"},
{"de": "die Zunahme", "satz": "Es wurde eine starke Zunahme der Erdbevölkerung verzeichnet.", "en": "increase"},
{"de": "vernünftig", "satz": "Bitte sei vernünftig und zieh die Jacke an, es ist kalt draußen.", "en": "sensible"},
{"de": "zeigen", "satz": "Er zeigte mir das Haus, in dem er wohnt.", "en": "show"},
{"de": "differenzieren", "satz": "Besonders im kulturellen Bereich differenziert sich unsere Gesellschaft immer mehr.", "en": "differentiate"},
{"de": "die Landschaft", "satz": "Eine Landschaft mit Bergen gefällt mir besser.", "en": "landscape, countryside"},
{"de": "der Jugendliche", "satz": "Jugendliche unter 18 Jahren dürfen die Veranstaltung nicht besuchen.", "en": "adolescent"},
{"de": "pro", "satz": "Ich trinke zwei Tassen Kaffee pro Tag.", "en": "per"},
{"de": "demonstrieren", "satz": "Viele Menschen haben für höhere Löhne und gegen Arbeitszeiterhöhung demonstriert.", "en": "demonstrate"},
{"de": "untereinander", "satz": "Es ist wichtig, dass ihr euch untereinander gut versteht.", "en": "among (our-)selves, each other"},
{"de": "aufnehmen", "satz": "Ich habe dir den Film auf Video aufgenommen.", "en": "record, include"},
{"de": "bewerten", "satz": "Die Lehrerin hat die Prüfung mit der Note „sehr gut“ bewertet.", "en": "assess, judge"},
{"de": "der Himmel", "satz": "Heute ist super Wetter, keine einzige Wolke am Himmel.", "en": "sky, heaven"},
{"de": "die Erkenntnis", "satz": "Ich bin zu der Erkenntnis gekommen, dass diese Arbeit nicht gut für mich ist.", "en": "realization, discovery"},
{"de": "minimal", "satz": "Die Ergebnisse unterscheiden sich nur minimal.", "en": "minimal"},
{"de": "verkaufen", "satz": "Ich werde mein Auto verkaufen, da ich fast nur noch mit dem Fahrrad unterwegs bin.", "en": "sell"},
{"de": "die Diskussion", "satz": "Wir müssen die Diskussion leider an dieser Stelle abbrechen.", "en": "discussion, debate"},
{"de": "die Wirtschaftspolitik", "satz": "Die Europäische Union hat noch keine gemeinsame Wirtschaftspolitik.", "en": "economic policy"},
{"de": "sicher", "satz": "Die Polizei hat einen sicheren Beweis, wer der Täter ist.", "en": "safe, secure, certain"},
{"de": "unabhängig", "satz": "Ich bin von meinem Mann finanziell unabhängig.", "en": "independent"},
{"de": "trösten", "satz": "Immer wenn ich traurig war, hat mich meine Mutter getröstet.", "en": "comfort"},
{"de": "mutmaßlich", "satz": "Sie halten ihn für den mutmaßlichen Täter.", "en": "presumed, suspected"},
{"de": "die Weile", "satz": "Es hat eine Weile gedauert, bis ich das verstanden habe.", "en": "while"},
{"de": "der Profi", "satz": "Tom ist Profi. Er hat viel Erfahrung.", "en": "pro, professional"},
{"de": "damals", "satz": "Als wir damals zusammen studierten, lebte sein Vater noch.", "en": "then"},
{"de": "leer", "satz": "Du trinkst zu schnell, dein Glas ist schon wieder leer!", "en": "empty"},
{"de": "einmalig", "satz": "Er bekam eine einmalige Zahlung von 1000 Euro.", "en": "unique, fantastic"},
{"de": "namens", "satz": "Eine Frau namens Hermann hat gestern angerufen.", "en": "by the name of, called"},
{"de": "die Bestellung", "satz": "Bitte bestätigen Sie Ihre Bestellung innerhalb von drei Tagen.", "en": "order, reservation"},
{"de": "das Arbeitsamt", "satz": "Das Arbeitsamt sucht neue Jobs für Leute, die arbeitslos sind.", "en": "employment office"},
{"de": "der Ingenieur", "satz": "Als Ingenieur arbeitet man meist in einem Bereich, der viel mit Technik zu tun hat.", "en": "engineer"},
{"de": "weich", "satz": "Dieses Bett ist mir zu weich, darin schlafe ich schlecht.", "en": "soft"},
{"de": "die Stabilität", "satz": "Einige Geschäfte gewährleisten die Stabilität ihrer Preise für die nächsten sechs Monate.", "en": "stability"},
{"de": "die Königin", "satz": "Zum Geburtstag der Königin findet ein großes Fest im Schloss statt.", "en": "queen"},
{"de": "das Urteil", "satz": "Zwei Jahre Gefängnis, so lautet das Urteil des Gerichts.", "en": "sentence, judgement"},
{"de": "die Vorbereitung", "satz": "Er hat die Vorbereitung für seine Prüfung nicht ernst genommen.", "en": "preparation"},
{"de": "das Frühstück", "satz": "Zum Frühstück esse ich manchmal ein Ei.", "en": "breakfast"},
{"de": "offiziell", "satz": "Die Nachricht wurde noch nicht offiziell bestätigt.", "en": "official"},
{"de": "die Ferne", "satz": "In der Ferne siehst du schon das Meer.", "en": "distance"},
{"de": "das Phänomen", "satz": "Starker Regen ist in dieser Jahreszeit ein häufiges Phänomen.", "en": "phenomenon"},
{"de": "der Skandal", "satz": "Während der letzten Sitzung des Parlaments kam es zu einem Skandal.", "en": "scandal"},
{"de": "der Abgeordnete", "satz": "Der Abgeordnete hält eine Rede im Bundestag.", "en": "member of parliament, congress"},
{"de": "der Palästinenser", "satz": "Er lebt in Deutschland, ist aber ursprünglich Palästinenser.", "en": "Palestinian"},
{"de": "die Maschine", "satz": "Die neue Maschine funktioniert gut.", "en": "machine"},
{"de": "die Bewegung", "satz": "Regelmäßige Bewegung ist wichtig für die Gesundheit.", "en": "exercise, movement, motion"},
{"de": "die Halle", "satz": "Wenn es regnet, können wir auch in der Halle Fußball spielen.", "en": "hall"},
{"de": "lediglich", "satz": "Lediglich fünf von zehn Schülern beginnen ein Studium.", "en": "merely"},
{"de": "kühl", "satz": "Im Sommer trinke ich am liebsten kühle Getränke.", "en": "cool"},
{"de": "der Komponist", "satz": "Johann Sebastian Bach war ein berühmter Komponist.", "en": "composer"},
{"de": "der Aufbau", "satz": "Der Artikel hat einen logischen Aufbau.", "en": "structure, construction"},
{"de": "ewig", "satz": "Er hat ihr ewige Liebe versprochen.", "en": "eternal"},
{"de": "das Café", "satz": "Wollen wir uns in dem Café am Rathaus treffen?", "en": "coffee house"},
{"de": "das Boot", "satz": "Wir sind mit dem Boot auf den See gefahren und haben Fische gefangen.", "en": "boat"},
{"de": "verdanken", "satz": "Er verdankt diesen Ärzten sein Leben.", "en": "owe, have sb thank for sth"},
{"de": "das Fenster", "satz": "Kannst du bitte das Fenster öffnen?", "en": "window"},
{"de": "der Doktor", "satz": "Der Doktor hat mir empfohlen, viel zu trinken.", "en": "doctor"},
{"de": "beitragen", "satz": "Jeder Einzelne kann etwas zum Schutz des Klimas beitragen.", "en": "contribute"},
{"de": "herrschen", "satz": "Früher herrschten in einigen europäischen Ländern Könige.", "en": "rule"},
{"de": "der Star", "satz": "In dem neuen Film spielen viele internationale Stars mit.", "en": "star, starling"},
{"de": "weltweit", "satz": "Die weltweite Zusammenarbeit in der internationalen Politik ist sehr wichtig.", "en": "world-wide"},
{"de": "wehen", "satz": "An der Küste weht immer ein sehr frischer Wind.", "en": "blow, flutter"},
{"de": "erste (r, s)", "satz": "Jan ist als erster Fahrer ins Ziel gekommen.", "en": "first"},
{"de": "die Scheibe", "satz": "Er putzt die Scheibe des Fensters.", "en": "glass pane, disc, slice"},
{"de": "stimmen", "satz": "Der Lehrer sagte mir, dass meine Rechnung nicht stimmt.", "en": "be correct, vote, tune"},
{"de": "anfangs", "satz": "Anfangs stand ich der Beziehung kritisch gegenüber.", "en": "initially"},
{"de": "zusätzlich", "satz": "Bevor ich mit der Arbeit anfange, benötige noch zusätzliche Informationen.", "en": "additional"},
{"de": "die Spitze", "satz": "Auf der Spitze des Baums sitzt ein Vogel und singt.", "en": "top, peak, point"},
{"de": "die Auflösung", "satz": "Am 19. Juni findet die Auflösung meiner Wohnung statt.", "en": "dissolving"},
{"de": "davor", "satz": "Heute Abend bekommen wir Besuch, davor müssen wir noch einkaufen gehen.", "en": "before it"},
{"de": "einst", "satz": "Einst war das Telefonieren in Deutschland teuer, heute ist es billig.", "en": "once, at one time, one day"},
{"de": "der Termin", "satz": "Ich habe morgen einen Termin beim Professor, zu dem ich nicht zu spät kommen darf.", "en": "appointment, date"},
{"de": "niedrig", "satz": "Pass auf, dass du dir nicht den Kopf stößt – die Decke im Keller ist sehr niedrig.", "en": "low, base"},
{"de": "erfüllen", "satz": "Ihr Hobby Tanzen erfüllt sie sehr.", "en": "grant, fulfill"},
{"de": "weitergeben", "satz": "Ich habe seine Information weitergegeben.", "en": "pass on"},
{"de": "zurzeit", "satz": "Das Theater ist zurzeit wegen Reparaturen geschlossen.", "en": "at the moment"},
{"de": "treten", "satz": "Das Mädchen trat kräftig gegen den Ball.", "en": "step"},
{"de": "das Zimmer", "satz": "In meinem Haus gibt es zehn Zimmer.", "en": "room"},
{"de": "produktiv", "satz": "Unser Unternehmen war in den letzten Jahren sehr produktiv.", "en": "productive"},
{"de": "die Abschreibung", "satz": "Bei einer Abschreibung wird der Wert eines Objekts, zum Beispiel eines Autos, heruntergesetzt, wenn es älter wird.", "en": "deduction, depreciation"},
{"de": "mithilfe", "satz": "Der Täter konnte mithilfe der Zeugen verurteilt werden.", "en": "with the aid"},
{"de": "die Gunst", "satz": "Ein junger Mann wollte die Gunst des hübschen Mädchens erwerben.", "en": "goodwill, favor"},
{"de": "bringen", "satz": "Bringst du bitte das Paket zur Post?", "en": "bring, take"},
{"de": "die Wäsche", "satz": "Sie hängt die Wäsche in den Garten, damit sie trocken wird.", "en": "washing, laundry"},
{"de": "hören", "satz": "In der Ferne hörte er die Stimme seiner Frau.", "en": "hear"},
{"de": "der Eigentümer", "satz": "Der Eigentümer des Hauses wohnt gleich gegenüber.", "en": "owner"},
{"de": "ermitteln", "satz": "Die Polizei konnte die Täter bislang nicht ermitteln.", "en": "find out, investigate"},
{"de": "herausstellen", "satz": "Es stellte sich heraus, dass ein anderer Mann das Geld gestohlen hatte.", "en": "come light, emphasize"},
{"de": "das Lokal", "satz": "Wir gehen am liebsten in das kleine Lokal an der Ecke, weil es dort am billigsten ist.", "en": "pub, bar"},
{"de": "einbauen", "satz": "In unserem Bad bauen wir demnächst eine neue Tür ein.", "en": "install, build in, fit"},
{"de": "zurückhalten", "satz": "Aus Angst vor einer erneuten Krise hielt die Regierung wichtige Informationen zurück.", "en": "hold back, restrain"},
{"de": "die Anzeige", "satz": "Nachdem man mir mein Fahrrad gestohlen hatte, habe ich bei der Polizei eine Anzeige gemacht.", "en": "report to the police"},
{"de": "die Übernahme", "satz": "Der Betrieb ist Opfer einer Übernahme durch einen anderen Betrieb geworden.", "en": "takeover"},
{"de": "studieren", "satz": "Seine Freundin studiert Geschichte und Germanistik an der Universität Leipzig.", "en": "study"},
{"de": "divers", "satz": "Diverse Kunden waren nicht zufrieden mit dem Produkt.", "en": "diverse, various"},
{"de": "bergen", "satz": "Die Feuerwehr konnte die Familie aus dem brennenden Haus bergen.", "en": "rescue, hide"},
{"de": "für", "satz": "Ich habe eine Nachricht für Frau Meier.", "en": "for"},
{"de": "erwidern", "satz": "Auf die Frage nach ihrem Alter erwiderte sie nichts.", "en": "reply"},
{"de": "stetig", "satz": "Die Zahl der Besucher hat in den letzten Jahren stetig zugenommen.", "en": "constant"},
{"de": "hübsch", "satz": "Das Hemd hat eine hübsche Farbe.", "en": "pretty"},
{"de": "die Woche", "satz": "Ein Jahr hat etwa 52 Wochen.", "en": "week"},
{"de": "darunter", "satz": "Was versteht man eigentlich darunter?", "en": "under it"},
{"de": "speichern", "satz": "Viele Unternehmen speichern die Daten ihrer Kunden.", "en": "store, save"},
{"de": "täglich", "satz": "Wer täglich Sport treibt, lebt länger, heißt es.", "en": "daily"},
{"de": "weisen", "satz": "Zwei Studenten wiesen mir den Weg zur Bibliothek.", "en": "point"},
{"de": "der Führer", "satz": "Durch das Museum begleitet sie ein Führer, der ihnen Informationen gibt.", "en": "leader, guide"},
{"de": "sterben", "satz": "Der junge Mann starb an den Folgen eines Unfalls.", "en": "die"},
{"de": "der Politiker", "satz": "Als Politiker sollte man gut mit den Medien umgehen können.", "en": "politician"},
{"de": "der Bruder", "satz": "Mein Bruder ist drei Jahre älter als ich und heißt Sebastian.", "en": "brother"},
{"de": "einsetzen", "satz": "Bereits mit wenigen Monaten setzt die sprachliche Entwicklung eines Kindes ein.", "en": "start, put in, insert"},
{"de": "bekämpfen", "satz": "Aufgabe der Polizei ist es, Verbrechen zu bekämpfen.", "en": "fight, combat"},
{"de": "der Lohn", "satz": "Diesen Monat habe ich meinen Lohn noch nicht bekommen.", "en": "wage, pay, reward"},
{"de": "begleiten", "satz": "Am Samstag werde ich meine Großmutter ins Theater begleiten.", "en": "accompany"},
{"de": "die Republik", "satz": "Von 1949 bis 1990 bestand Deutschland aus zwei sehr unterschiedlichen Republiken.", "en": "republic"},
{"de": "der Job", "satz": "Ich suche seit einem halben Jahr nach einem neuen Job.", "en": "job"},
{"de": "das Training", "satz": "Wenn das Training heute nicht so hart wird, können wir abends noch ins Kino gehen.", "en": "training"},
{"de": "voraus", "satz": "Er ist mir immer einen Schritt voraus.", "en": "ahead, foreward"},
{"de": "fällig", "satz": "Die Rechnung für letzten Monat ist morgen fällig.", "en": "due"},
{"de": "die Spur", "satz": "Die Spur führte die Polizei zu einem einsamen Haus, wo sie schließlich den Täter fand.", "en": "track, lane"},
{"de": "verbinden", "satz": "Verbinden Sie mich bitte mit dem Leiter der Einrichtung!", "en": "connect, link"},
{"de": "das Gewissen", "satz": "Ich habe immer ein schlechtes Gewissen, wenn ich viel Eis esse.", "en": "conscience"},
{"de": "deswegen", "satz": "Alle haben eine andere Meinung. Deswegen ist es noch zu keiner Einigung gekommen.", "en": "therefore, that's why"},
{"de": "beurteilen", "satz": "Man sollte diesen Test nicht zu streng beurteilen.", "en": "assess, judge"},
{"de": "die Ermittlung", "satz": "Die Ermittlungen der Polizei sind noch nicht abgeschlossen.", "en": "investigation"},
{"de": "produzieren", "satz": "Diese Firma produziert hochwertige Möbel aus Holz.", "en": "produce"},
{"de": "der Gegensatz", "satz": "Der Gegensatz zu stark ist schwach.", "en": "opposite, contrast"},
{"de": "sonstig", "satz": "Sonstige Kosten werden nicht bezahlt.", "en": "other"},
{"de": "das Immunsystem", "satz": "AIDS ist eine Krankheit, die das Immunsystem zerstört.", "en": "immune system"},
{"de": "anvertrauen", "satz": "Ihre Sorgen vertraute sie ihrem Freund an.", "en": "entrust, confide"},
{"de": "die Sendung", "satz": "Die Sendung über den Besuch des amerikanischen Präsidenten in Berlin wird morgen wiederholt.", "en": "broadcast"},
{"de": "der Bundesrat", "satz": "Der Bundesrat besteht aus Vertretern der Bundesländer Deutschlands.", "en": "Upper House of Parliament"},
{"de": "der Rücktritt", "satz": "Nach längeren Debatten hat der Kanzler nun seinen Rücktritt erklärt.", "en": "resignation"},
{"de": "nennen", "satz": "Sie nannten ihre Tochter Laura.", "en": "name, call"},
{"de": "das Produkt", "satz": "In diesem Geschäft werden regionale Produkte angeboten.", "en": "product"},
{"de": "der Rhythmus", "satz": "Sie mag besonders Musik mit einem schnellen Rhythmus.", "en": "rhythm"},
{"de": "der Typ", "satz": "Mein Bruder ist ein ganz ruhiger Typ.", "en": "type"},
{"de": "unglücklich", "satz": "Viele Menschen sind einsam und unglücklich.", "en": "unhappy, unfortunate"},
{"de": "der Zins", "satz": "Wenn man sein Geld bei einer Bank anlegt, bekommt man dafür Zinsen.", "en": "interest"},
{"de": "abzeichnen", "satz": "Leider zeichnet sich noch immer keine Verbesserung auf dem Arbeitsmarkt ab.", "en": "become apparent, stand out, draw"},
{"de": "also", "satz": "Wir müssen also davon ausgehen, dass die Aktien weiter fallen.", "en": "so"},
{"de": "wiedersehen", "satz": "Er freute sich, seinen ehemaligen Kollegen nach all den Jahren wiederzusehen.", "en": "see again"},
{"de": "verfallen", "satz": "Auch wenn das Konzert kurzfristig verschoben wird, verfallen unsere Karten nicht.", "en": "expire, deteriorate"},
{"de": "ehrlich", "satz": "Ein ehrlicher Mensch sagt meistens, was er denkt.", "en": "honest"},
{"de": "das Schloss", "satz": "Der König wohnt mit seiner Familie in einem riesigen Schloss.", "en": "castle, lock"},
{"de": "klinisch", "satz": "Klinische Tests haben die Wirkung des Medikamentes bestätigt.", "en": "clinical"},
{"de": "ausgehen", "satz": "Heute Abend will Alexander mit seiner Freundin ausgehen.", "en": "go out, assume"},
{"de": "sehen", "satz": "Aus dieser Entfernung ist die Stadt kaum noch zu sehen.", "en": "see"},
{"de": "die Vertretung", "satz": "Wenn der Chef krank ist, übernimmt sein Kollege die Vertretung in der Firma.", "en": "replacement, substitute"},
{"de": "der Tanz", "satz": "Der junge Mann bat mich um einen Tanz.", "en": "dance"},
{"de": "die Fähigkeit", "satz": "Zum Studieren gehören auch soziale Fähigkeiten.", "en": "ability, capability"},
{"de": "organisch", "satz": "Der Unfall hat bei ihm keine organischen Schäden verursacht.", "en": "organic"},
{"de": "beschließen", "satz": "Der Bundestag hat gestern ein neues Gesetz zum Schutz von Kindern beschlossen.", "en": "decide"},
{"de": "das Licht", "satz": "Das Licht ist am Morgen noch nicht sehr hell.", "en": "light"},
{"de": "erstellen", "satz": "Der Autor erstellt eine Konzeption für sein nächstes Buch.", "en": "draw up, build, produce"},
{"de": "transportieren", "satz": "Viele Waren werden von LKWs durch die gesamte Bundesrepublik transportiert.", "en": "transport"},
{"de": "der Bericht", "satz": "Im Radio kam gestern Abend ein Bericht über die Arbeitslosigkeit in Sachsen.", "en": "report"},
{"de": "verstehen", "satz": "Ich verstehe dich und deine Zweifel sehr gut.", "en": "understand"},
{"de": "die Geduld", "satz": "Mit etwas Geduld geht bei schwierigen Situationen alles besser.", "en": "patience"},
{"de": "spannend", "satz": "Dieses Buch ist sehr spannend, ich habe es an einem Abend zu Ende gelesen.", "en": "exciting, thrilling"},
{"de": "Fakten", "satz": "In dieser Zeitung lesen sie die harten Fakten.", "en": "facts"},
{"de": "beauftragen", "satz": "Er hat seine Mitarbeiter beauftragt, die nächste Sitzung vorzubereiten.", "en": "give sb the task of doing sth, hire (a firm)"},
{"de": "einerseits", "satz": "Einerseits lebe ich gerne in der Stadt, andererseits fehlt mir die Natur.", "en": "on the one hand"},
{"de": "lügen", "satz": "Es stimmt nicht, was er sagt. Er lügt.", "en": "tell a lie, lie"},
{"de": "teilen", "satz": "Mit meinem besten Freund teile ich viele Geheimnisse.", "en": "share, divide"},
{"de": "der Stolz", "satz": "Die hervorragende Leistung seiner Tochter erfüllte ihn mit Stolz.", "en": "pride"},
{"de": "die Diagnose", "satz": "Wir müssen einige Untersuchungen machen, damit wir eine Diagnose stellen können.", "en": "diagnosis"},
{"de": "die Wüste", "satz": "In der Wüste ist es am Tag sehr heiß und in der Nacht kalt.", "en": "desert"},
{"de": "beide", "satz": "Sie haben beide die Trennung gewollt.", "en": "both"},
{"de": "versinken", "satz": "Wenn die Sonne versinkt, ist der Himmel rot.", "en": "sink"},
{"de": "ein", "satz": "Heute ist ein schöner Tag.", "en": "a"},
{"de": "die Uniform", "satz": "Soldaten tragen eine Uniform.", "en": "uniform"},
{"de": "bewusst", "satz": "Sie achtet sehr bewusst auf ihre Ernährung.", "en": "conscious"},
{"de": "herum", "satz": "Wir sind einmal um den See herum gelaufen.", "en": "around"},
{"de": "erklären", "satz": "Der Lehrer erklärt den Schülern die Aufgabe an einem Beispiel.", "en": "explain"},
{"de": "mitbringen", "satz": "Du kannst deine Schwester gern zur Party mitbringen.", "en": "bring"},
{"de": "eindeutig", "satz": "Die Schuld des Angeklagten ist eindeutig bewiesen.", "en": "clear"},
{"de": "doppelt", "satz": "Sie kauft die doppelte Menge an Äpfeln.", "en": "double"},
{"de": "der Sack", "satz": "Der Händler lädt zehn Säcke mit Kartoffeln auf seinen Wagen.", "en": "sack"},
{"de": "mitteilen", "satz": "Heute hat man mir den Termin für die Lieferung mitgeteilt.", "en": "inform"},
{"de": "die Anforderung", "satz": "Die Anforderungen an die Schüler werden immer größer.", "en": "request, demand"},
{"de": "der Wille", "satz": "Er hat einen starken Willen und hat nicht viele Probleme.", "en": "will"},
{"de": "scheinen", "satz": "Die Sonne scheint heute besonders warm.", "en": "shine, seem, appear"},
{"de": "die Germanistik", "satz": "Sie studiert in Leipzig Germanistik.", "en": "German studies"},
{"de": "schriftlich", "satz": "Die schriftliche Prüfung dauert vier Stunden.", "en": "written"},
{"de": "klug", "satz": "Mein Sohn ist sehr klug, er besucht das Gymnasium.", "en": "clever"},
{"de": "zuletzt", "satz": "Ich habe meine Eltern zuletzt zu Weihnachten gesehen.", "en": "last, in the end"},
{"de": "die Gründung", "satz": "Die Gründung der Firma war im Jahr 2004.", "en": "foundation"},
{"de": "hinzu", "satz": "Jetzt kommen zu dem Gericht noch drei Eier hinzu.", "en": "in addition"},
{"de": "konservativ", "satz": "Sie ist in einer konservativen Familie aufgewachsen. Ihre Eltern haben sie sehr kontrolliert.", "en": "conservative"},
{"de": "installieren", "satz": "Ein Experte für Informationstechnologie hat mir die neue Software installiert.", "en": "install"},
{"de": "umso", "satz": "Je mehr ich esse, umso dicker werde ich.", "en": "the (more ... the)"},
{"de": "der Abschluss", "satz": "Wer keinen Abschluss hat, findet schwer Arbeit.", "en": "degree, end, conclusion"},
{"de": "vier", "satz": "", "en": "four"},
{"de": "verwirklichen", "satz": "Sie hat ihren Traum von einer eigenen Ausstellung verwirklicht.", "en": "put in practice, carry out"},
{"de": "einziehen", "satz": "Neben uns ist eine junge Familie mit zwei Kindern eingezogen.", "en": "move in"},
{"de": "entstehen", "satz": "In trockenen Gebieten entstehen nur wenige Pflanzen.", "en": "originate, develop"},
{"de": "die Linse", "satz": "Die Linse meiner Kamera funktioniert nicht.", "en": "lens"},
{"de": "beten", "satz": "Er ist Christ und betet jeden Abend zu Gott.", "en": "pray"},
{"de": "christlich", "satz": "Die christliche Religion ist sehr alt.", "en": "Christian"},
{"de": "die Bearbeitung", "satz": "Für die Bearbeitung der Akten ist unsere Abteilung zuständig.", "en": "handling, working"},
{"de": "orientieren", "satz": "Auf dem Meer kann man sich an den Sternen orientieren.", "en": "orient"},
{"de": "ästhetisch", "satz": "Die Fotografien sind sehr ästhetisch.", "en": "aesthetic"},
{"de": "der Artikel", "satz": "Den Autor des Artikels kenne ich persönlich.", "en": "article"},
{"de": "die Lehre", "satz": "Er hat eine Lehre zum Verkäufer gemacht.", "en": "apprenticeship, lesson, doctrine"},
{"de": "die Sorge", "satz": "Ich mache mir große Sorgen um die Gesundheit meines Bruders.", "en": "worry"},
{"de": "der Wähler", "satz": "Der Wähler hat sein Kreuz auf dem Zettel gemacht.", "en": "voter"},
{"de": "jung", "satz": "Trotz seines hohen Alters ist er noch sehr jung geblieben.", "en": "young"},
{"de": "äußerst", "satz": "Deine Idee finde ich äußerst interessant.", "en": "extremely"},
{"de": "wachsen", "satz": "Im Wald wachsen viele verschiedene Pflanzen.", "en": "grow"},
{"de": "ermöglichen", "satz": "Das Internet ermöglicht es, schnell Informationen zu den verschiedensten Themen zu erhalten.", "en": "enable"},
{"de": "das Vorhaben", "satz": "Der Bau einer solchen Maschine ist ein teures, aber sehr interessantes Vorhaben.", "en": "plan, intention"},
{"de": "britisch", "satz": "Die britischen Autos fahren auf der linken Seite der Straße.", "en": "British"},
{"de": "die Unsicherheit", "satz": "Das stets verlegene Gesicht ist ein Zeichen für seine Unsicherheit.", "en": "uncertainty"},
{"de": "inhaltlich", "satz": "Der Bericht war inhaltlich nicht korrekt.", "en": "in terms of content"},
{"de": "mittlerweile", "satz": "Ich habe lange gewartet, mittlerweile glaube ich aber nicht mehr, dass er kommt.", "en": "in the meantime, since then"},
{"de": "der Schrank", "satz": "In unserem Wohnzimmer steht ein großer Schrank aus Holz.", "en": "cabinet, wardrobe"},
{"de": "sowieso", "satz": "Der Zug kommt sowieso immer zu spät, also reicht es auch, wenn wir ein wenig später zum Bahnhof gehen.", "en": "anyway"},
{"de": "besondere (r,s)", "satz": "Das ist ein ganz besonderes Buch.", "en": "special"},
{"de": "sein", "satz": "Sein Vater hat beruflich viel im Ausland zu tun.", "en": "his, its"},
{"de": "setzen", "satz": "Das Kind setzte sich auf die oberste Stufe der Treppe.", "en": "set, place, put"},
{"de": "jemals", "satz": "Ich bin glücklicher als jemals zuvor in meinem Leben.", "en": "ever"},
{"de": "der Buchstabe", "satz": "Das deutsche Alphabet hat 26 Buchstaben.", "en": "letter"},
{"de": "aufsetzen", "satz": "Bei Regen setzt er immer einen Hut auf.", "en": "put on"},
{"de": "das Seminar", "satz": "An diesem Seminar nehmen 30 Studenten teil.", "en": "seminar"},
{"de": "französisch", "satz": "Französischer Käse ist in Deutschland sehr beliebt.", "en": "French"},
{"de": "die Enttäuschung", "satz": "Es war eine große Enttäuschung, als er mich verließ.", "en": "disappointment"},
{"de": "meinen", "satz": "Was meinst du dazu?", "en": "think, have an opinion"},
{"de": "antun", "satz": "Wie konnte sie ihm das nur antun – sich gerade jetzt von ihm zu trennen?", "en": "do sth to sb"},
{"de": "zugänglich", "satz": "Der Eingang der Höhle ist schwer zugänglich.", "en": "accessible"},
{"de": "erhältlich", "satz": "Viele Zeitungen sind am Bahnhof erhältlich.", "en": "available"},
{"de": "verhandeln", "satz": "Über den Preis des Autos müssen wir erst noch verhandeln.", "en": "negotiate"},
{"de": "das Drittel", "satz": "Ein Drittel der Studenten hat die Prüfung nicht bestanden.", "en": "third"},
{"de": "kurz", "satz": "Ist das Kleid nicht etwas zu kurz?", "en": "short"},
{"de": "die Platte", "satz": "Ich habe noch viele alte Platten von den Rolling Stones.", "en": "record, disk"},
{"de": "die Entscheidung", "satz": "Du musst eine Entscheidung treffen: ja oder nein?", "en": "decision"},
{"de": "der Held", "satz": "Dieser Schauspieler spielt in Filmen meist einen Helden.", "en": "hero"},
{"de": "mehrmals", "satz": "Ich habe mehrmals versucht, dich anzurufen.", "en": "repeatedly"},
{"de": "vorerst", "satz": "Vorerst wohnen wir bei Freunden, später in einer eigenen Wohnung.", "en": "for the present"},
{"de": "die Zelle", "satz": "Pflanzen, Menschen und Tiere bestehen aus vielen Zellen.", "en": "cell"},
{"de": "das Vorgehen", "satz": "Das Vorgehen der Polizei wurde von vielen Leuten kritisiert.", "en": "action"},
{"de": "der Journalist", "satz": "Er arbeitet als Journalist und schreibt Artikel für diverse Zeitungen.", "en": "journalist"},
{"de": "übertragen", "satz": "Dieses Virus wird von Tieren auf den Menschen übertragen.", "en": "transfer"},
{"de": "umstritten", "satz": "Er ist ein umstrittener Schriftsteller, seine Texte stoßen auf viel Kritik.", "en": "disputed"},
{"de": "entnehmen", "satz": "Der Verkäufer entnahm zehn Euro aus der Kasse.", "en": "take, extract, infer"},
{"de": "der Eingang", "satz": "Der Eingang zum Hotel befindet sich in der Leninstraße.", "en": "entrance"},
{"de": "am", "satz": "Mein Auto ist am schnellsten.", "en": "the (+ superlative)"},
{"de": "trinken", "satz": "Zum Essen trinke ich gern ein Bier.", "en": "drink"},
{"de": "zirka, circa, ca.", "satz": "Von Berlin nach Hamburg sind es zirka 300 Kilometer.", "en": "approximately"},
{"de": "verschließen", "satz": "Sie verschloss die Tür ihres Zimmers, so dass die Mutter nicht eintreten konnte.", "en": "close, lock"},
{"de": "der März", "satz": "Bei uns beginnt im März der Frühling, während in Sydney dann der Herbst beginnt.", "en": "March"},
{"de": "die Verletzung", "satz": "Aufgrund dieser schlimmen Verletzung braucht der Patient einen Verband.", "en": "injury"},
{"de": "der Einfluss", "satz": "Der Einfluss der Kirche im Staat ist geringer geworden.", "en": "influence"},
{"de": "seither", "satz": "Als Kind habe ich viel Sport gemacht, seither bin ich sportlich.", "en": "since then"},
{"de": "wirklich", "satz": "Es ist wirklich so, wie ich es mir gedacht habe.", "en": "really, actually"},
{"de": "die Version", "satz": "Die neue Version des Programms hat noch Schwächen.", "en": "version"},
{"de": "betreiben", "satz": "Mein Bruder betreibt ein kleines Geschäft mit italienischer Mode.", "en": "operate, run"},
{"de": "das Orchester", "satz": "Das Orchester befindet sich gerade auf einer Tour durch Europa.", "en": "orchestra"},
{"de": "kochen", "satz": "Heute koche ich Kartoffeln und Fleisch.", "en": "cook"},
{"de": "schätzen", "satz": "Ich schätze vor allem seinen Einsatz für Kinder aus armen Familien.", "en": "value, estimate"},
{"de": "das Opfer", "satz": "Das letzte Opfer hat den Täter identifiziert.", "en": "victim, sacrifice"},
{"de": "keinerlei", "satz": "Das Medikament hatte keinerlei Wirkung.", "en": "no ... at all"},
{"de": "erfassen", "satz": "Wir werden Ihre persönlichen Daten am Telefon erfassen.", "en": "grasp"},
{"de": "das Merkmal", "satz": "Seine blauen Augen waren ein auffälliges Merkmal.", "en": "feature"},
{"de": "die Luft", "satz": "Die Luft auf dem Land ist sauberer als in der Stadt.", "en": "air"},
{"de": "verzichten", "satz": "Er hat auf seinen Anteil am Haus des verstorbenen Vaters verzichtet.", "en": "do without"},
{"de": "detailliert", "satz": "Der Artikel war sehr detailliert geschrieben.", "en": "detailed"},
{"de": "der Aufsatz", "satz": "Im Laufe des Semesters werden zwei Aufsätze geschrieben.", "en": "essay"},
{"de": "die Verordnung", "satz": "Es gibt eine Verordnung, die besagt, wie man sich im Verkehr verhalten muss.", "en": "prescription, order"},
{"de": "grundlegend", "satz": "Mit der neuen Regierung hat sich die Politik grundlegend geändert.", "en": "basic, fundamental"},
{"de": "hinfahren", "satz": "Er ist dann doch mit dem Zug hingefahren.", "en": "go there, drive there"},
{"de": "japanisch", "satz": "Die japanische Botschaft befindet sich, wie viele andere auch, in Berlin.", "en": "Japanese"},
{"de": "erhöhen", "satz": "Im letzten Jahr haben viele Geschäfte die Preise für Lebensmittel stark erhöht.", "en": "raise, increase"},
{"de": "resultieren", "satz": "Daraus resultiert, dass wir früher mit dem Projekt beginnen müssen.", "en": "result"},
{"de": "veranstalten", "satz": "Am Samstag veranstaltet unser Orchester ein Konzert.", "en": "organize"},
{"de": "die Eltern", "satz": "Meine Eltern haben sich beim Tanzen kennen gelernt.", "en": "parents"},
{"de": "die Einschätzung", "satz": "Die Einschätzung meiner Lehrerin war sehr positiv.", "en": "assessment, evaluation, opinion"},
{"de": "basieren", "satz": "Diese Erkenntnis basiert auf jahrelanger Erfahrung.", "en": "be based on"},
{"de": "bestreiten", "satz": "Vor dem Richter bestritten sie alle Vorwürfe.", "en": "dispute"},
{"de": "der Landkreis", "satz": "Ein Landkreis besteht aus vielen kleinen und großen Gemeinden.", "en": "district"}
];